#!/usr/bin/env bash

set -e

testNumber="04"

# Compiles
javac src/* -d output

# Executes and pipes the output
java -cp output Main < testing/input/input-$testNumber > testing/output/output-$testNumber

# Diffs to check
diff testing/output/output-$testNumber testing/answer/answer-$testNumber
