#!/usr/bin/env bash

set -e

testNumber="02"

# Compiles
javac src/*.java -d output

# Executes and pipes the output
java -cp output Main$testNumber < testing/input/input-$testNumber > testing/output/output-$testNumber

# Diffs to check
diff testing/output/output-$testNumber testing/answer/answer-$testNumber
